language: python

python:
  - "3.8"

services:
  - docker

before_install:
  - docker-compose run --user='root' --entrypoint chown django -R django:djangogroup .
  - docker-compose build

script:
  - docker-compose run django /bin/bash docker/commands/test.sh